# @name HealthCheck
GET http://localhost:3333

###

# @name ListAllPrompts
GET http://localhost:3333/prompts

###

# @name UploadVideo
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name CreateTranscriptionOfVideo
POST http://localhost:3333/videos/a8df5e29-f4a1-4447-967a-21b9448f4ba9/transcription
Content-Type: application/json

{
    "prompt": "Teste do áudio, saudação"
}

###

# @name GenerateAICompletion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
    "videoId": "a8df5e29-f4a1-4447-967a-21b9448f4ba9",
    "temperature": 0.5,
    "template": "Gere um resumo sucinto da transcrição do vídeo informada a seguir: '''{transcription}'''"
}